name: clarsentest
favicon: null
layout_spectrum: 0.12059
typography_spectrum: 0.05767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363b3e'
    - '#59636c'
    - '#93a0a9'
    - '#f5ffff'
    - '#c8573c'
  brandStrength: 1
  lightness: 0.7510181327816099
  saturation: 0.8125
  rhythmicContrast: 0.8350667217746377
purpose: []
