name: clarsentest
favicon: null
layout_spectrum: 0.12059
typography_spectrum: 0.05767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1d'
    - '#6d9eac'
    - '#e04614'
    - '#fafafa'
    - '#5d5d5d'
  brandStrength: 0.5286578100640327
  lightness: 0.7510181327816099
  saturation: 0.8030938864685595
  rhythmicContrast: 0.8350667217746377
purpose: []
